version: "3.7"

services:
  server:
    build: .
    container_name: thoth
    image: thoth
    ports:
      - "5555:5555"
      - "8081:8081"
    environment:
      OTEL_SERVICE_NAME: thoth
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://tempo:14268/api/traces
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3101/loki/api/v1/push'

  tempo:
    image: grafana/tempo:1.0.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./etc/tempo.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/tmp/tempo
    ports:
      - "14268"      # jaeger ingest, Jaeger - Thrift HTTP
      - "14250"      # Jaeger - GRPC
      - "55680"      # OpenTelemetry
      - "3100"       # tempo
      - "6831/udp"   # Jaeger - Thrift Compact
      - "6832/udp"   # Jaeger - Thrift Binary    
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3101/loki/api/v1/push'

  loki:
    image: grafana/loki:2.2.1
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3101:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    volumes:
      - ./etc/loki.yaml:/etc/loki/loki.yaml
      - ./data/loki-data:/tmp/loki
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3101/loki/api/v1/push'

  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus.yaml" ]
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3101/loki/api/v1/push'

  grafana:
    image: grafana/grafana:8.1.0-ubuntu
    volumes:
      - ./etc/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3101/loki/api/v1/push'